#!/usr/bin/env python3
"""Render CATALOG.md from catalog/models.json."""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "catalog" / "models.json"
TARGET = ROOT / "CATALOG.md"

SECTIONS = [
    ("genomics", "Genomics", "Ordered DNA, variation, and sequence-to-function regulatory models."),
    ("transcriptomics", "Transcriptomics and single-cell", "Sparse gene-expression programs and virtual-cell backbones."),
    ("proteomics", "Protein and proteomics", "Protein sequence/structure models plus models of measured proteomic spectra."),
    ("rna", "RNA", "RNA sequence, structure, isoform, and function models."),
    ("epigenomics", "Epigenomics", "Chromatin accessibility and context-specific regulatory models."),
    ("spatial-omics", "Spatial omics", "Molecular measurements whose coordinates and neighborhoods are part of the input grammar."),
    ("metabolomics", "Metabolomics", "Mass-spectrum representations and spectrum-to-molecule alignment."),
    ("cross-omics", "Cross-omics translators", "Models or systems explicitly aligning or generating across biological modalities."),
]


def escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def artifact_links(item: dict) -> str:
    links: list[str] = []
    if item["code"]:
        links.append(f"[code]({item['code']})")
    if item["weights"]:
        links.append(f"[weights/API]({item['weights']})")
    return " · ".join(links) if links else "—"


def render(records: list[dict]) -> str:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for item in records:
        grouped[item["primary_omics"]].append(item)

    lines = [
        "# Model catalog",
        "",
        "<!-- Generated by scripts/render_catalog.py. Edit catalog/models.json, not this file. -->",
        "",
        f"**{len(records)} curated entries · literature sweep through 2026-08-25**",
        "",
        "Status: **PR** = peer-reviewed · **PP** = preprint · **R** = released artifact. The tables are descriptive, not rankings.",
        "",
    ]

    status_label = {"peer-reviewed": "PR", "preprint": "PP", "released": "R"}
    for key, title, description in SECTIONS:
        lines.extend([f"## {title}", "", description, ""])
        items = sorted(grouped.get(key, []), key=lambda item: (-item["year"], item["name"].lower()))
        if not items:
            lines.extend(["_No entries._", ""])
            continue
        lines.extend(
            [
                "| Model | Year | Input language | Output / translation | Scale | Artifacts |",
                "|---|---:|---|---|---|---|",
            ]
        )
        for item in items:
            model = f"[{escape(item['name'])}]({item['paper']})"
            year = f"{item['year']} {status_label[item['status']]}"
            lines.append(
                "| "
                + " | ".join(
                    [
                        model,
                        year,
                        escape(item["input_language"]),
                        escape(item["output_language"]),
                        escape(item["scale"]),
                        artifact_links(item),
                    ]
                )
                + " |"
            )
        lines.append("")

    lines.extend(
        [
            "## Reading the table",
            "",
            "- A code link does not imply that model weights or outputs have an unrestricted license.",
            "- `Input language` describes the actual computational representation, not the broad biological field name.",
            "- `Output / translation` distinguishes embeddings, prediction, alignment, and conditional generation.",
            "- See [selection method](docs/selection-method.md) for evidence and inclusion rules.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when CATALOG.md is not up to date.")
    args = parser.parse_args()

    records = json.loads(SOURCE.read_text(encoding="utf-8"))
    content = render(records)
    if args.check:
        existing = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if existing != content:
            print("CATALOG.md is stale; run python scripts/render_catalog.py", file=sys.stderr)
            return 1
        print("CATALOG.md is up to date.")
        return 0

    TARGET.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {TARGET.relative_to(ROOT)} with {len(records)} entries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
